QUANDL = "https://www.quandl.com/api/v3/datasets/WIKI/"
BSE_META = "https://www.quandl.com/api/v3/databases/BSE"
BSE_ID = "https://www.quandl.com/api/v3/datasets"
QUANDL_API_KEY = "kXzs8KXhFUFWf6-q7so9"
NSE_META = "https://www.nseindia.com/content/equities/EQUITY_L.csv"
NSE_DATA = "https://www.nseindia.com/live_market/dynaContent/live_watch/get_quote/getHistoricalData.jsp?symbol=TCS&series=EQ&fromDate=25-12-2015&toDate=04-01-2019"
